version: '3'

services:

  mongocontainer:
    image: mongo:4.4.1
    ports:
    - 27017:27017
    networks:
    - net-spring-db

  mongo-init:
    build: ./mongo-init
    depends_on:
    - mongocontainer
    networks:
    - net-spring-db

networks:
  net-spring-db:
    driver: bridge